# Generated by Django 4.2.1 on 2023-05-26 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('outher', models.CharField(blank=True, max_length=50, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retalprice', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retalperiod', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
                ('outherimage', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('availble', 'availble'), ('retaled', 'retaled'), ('seald', 'seald')], max_length=50, null=True)),
                ('Categry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.categry')),
            ],
        ),
    ]
