# Generated by Django 4.2.1 on 2023-05-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_books_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categry',
            new_name='Categrymodel',
        ),
    ]
